apiVersion: v1
kind: Service
metadata:
  name: takelock
  labels:
    app: takelock
spec:
  ports:
    - port: 50051
      name: takelock-http
  selector:
    app: takelock-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: takelock-app
  labels:
    app: takelock-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: takelock-app
  template:
    metadata:
      labels:
        app: takelock-app
    spec:
      containers:
        - name: takelock-app
          image: takelock-app
          ports:
            - containerPort: 50051
              name: http
          env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          volumeMounts:
            - mountPath: /etc/podinfo
              name: podinfo
      volumes:
        - name: podinfo
          downwardAPI:
            items:
              - path: "labels"
                fieldRef:
                  fieldPath: metadata.labels
              - path: "annotations"
                fieldRef:
                  fieldPath: metadata.annotations
