apiVersion: v1
kind: Service
metadata:
  name: protected
  labels:
    app: protected
spec:
  ports:
    - port: 50001
      name: protected-http
  selector:
    app: protected-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: protected-app
  labels:
    app: protected-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: protected-app
  template:
    metadata:
      labels:
        app: protected-app
    spec:
      containers:
        - name: protected-app
          image: protected-app
          ports:
            - containerPort: 50001
              name: http
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name